Fruit and Insects: gameManager Class Reference
gameManager Class Reference
our main glwindow widget for NGL applications all drawing elements are put in this file. it is the game's main class and create the game world with all its haracters. it checks for collisions between the falling characters and the basket
#include <gameManager.h>
Public Slots
void exit_game ()
slot to exit the game from UI exit button
void setPlay ()
slot to play the game from UI play button
void setPause ()
slot to pause the game from UI pause button
void setResume ()
slot to resume the game from UI resume button
Signals
void updateShield ()
signal to update the shield value in UI
void updateScore ()
signal to update the score in UI
Public Member Functions
gameManager (QWidget *_parent)
Constructor for GLWindow.
~gameManager ()
dtor add any code here to tidy up
void processKeyDown (QKeyEvent *_event)
processKeyDown passed from the main window class
void processKeyUp (QKeyEvent *_event)
processKeyUp passed from the main window class
void moveBasket_gl ()
method to move the basket with every key press updates the basket position with respect to arrow keys in x and z axis calls the move funtion of basket class to update basket position
void moveFallingChars_gl ()
method to call the move method of fallingChars class
int catchProgress ()
method to check the progress in number of catches made by basket
int shieldLeft ()
method to return the shield value of the basket
int playerScore ()
method to return the score
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Private Member Functions
void checkCatch ()
method to check if there is a catch by basket calls the collsion detection method to validate a check
bool basketFallingCharCollision (ngl::Vec3 _pos1, float _rad1, ngl::Vec3 _pos2, float _rad2)
method to check the collision between basket and falling characters
void timerEvent (QTimerEvent *_event)
the timer event triggered from the timers
void loadMatricesToShader (ngl::TransformStack &_tx)
method to load the tx stack (+MVP) to the shader
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void wheelEvent (QWheelEvent *_event)
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Private Attributes
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
bool m_translate
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Vec3 m_modelPos
the model position for mouse movement
int m_updateTimer
a timer triggered by the startTimer call in the ctor this is called to update the basket position based on the key presses
int m_redrawTimer
ngl::Camera * m_cam
game Camera
ngl::TransformStack m_transformStack
transform stack for drawing
QSet< Qt::Key > m_keysPressed
the keys being pressed
ngl::Light * m_light
the light
gameEntities m_gameentity
the gameEntity class for all game meshes
basket * m_Basket
the basket class pointer
fallingChars * m_fallingChars
the fallingChar class pointer
gameGround * m_gameGround
the gameGround class pointer
gameWorld * m_gameWorld
the gameWorld class pointer
int catchCount
counter to keep track of number of catches
ngl::Text * m_hud
text for game's heads up display
bool playFlag
flag to play or stop the game
bool pauseFLag
flag to pause the game
Detailed Description
our main glwindow widget for NGL applications all drawing elements are put in this file. it is the game's main class and create the game world with all its haracters. it checks for collisions between the falling characters and the basket
Definition at line 62 of file gameManager.h.
Constructor & Destructor Documentation
gameManager::gameManager (QWidget * _parent)
Constructor for GLWindow.
Parameters:
[in] _parent the parent window to create the GL context in
Definition at line 27 of file gameManager.cpp.
References m_keysPressed, m_origX, m_origY, m_redrawTimer, m_rotate, m_spinXFace, m_spinYFace, m_updateTimer, pauseFLag, and playFlag.
                                        : QGLWidget( new CreateCoreGLContext(QGLFormat::defaultFormat()), _parent )
{
    // set this widget to have the initial keyboard focus
    setFocus();
    // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
    this->resize(_parent->size());
    // now we start a timer and assign it to the g_updatetimer_basket variable
    m_updateTimer = startTimer(60);
    m_redrawTimer = startTimer(120);
    // clear the key set
    m_keysPressed.clear();
    //game play and pause flags
    playFlag = false;
    pauseFLag = false;
    //mouse rotation values set to 0
    m_rotate=false;
    m_spinXFace=0;
    m_spinYFace=0;
    m_origX=0;
    m_origY=0;
}
gameManager::~gameManager ()
dtor add any code here to tidy up
Definition at line 49 of file gameManager.cpp.
References m_Basket, m_cam, m_fallingChars, m_gameGround, m_gameWorld, and m_light.
{
    delete m_gameWorld;
    delete m_gameGround;
    delete m_fallingChars;
    delete m_Basket;
    delete m_light;
    delete m_cam;
}
Member Function Documentation
bool gameManager::basketFallingCharCollision (ngl::Vec3 _pos1, float _rad1, ngl::Vec3 _pos2, float _rad2) [private]
method to check the collision between basket and falling characters
Parameters:
_pos1 basket's position
_rad1 basket's radius
_pos2 falling character's position
_rad2 falling character's radius
Definition at line 328 of file gameManager.cpp.
{
    ngl::Vec3 relPos;
    //distance between basket and falling char
    GLfloat dist;
    GLfloat minDist;
    GLfloat len;
    relPos = _pos1 - _pos2;
    len = relPos.length();
    dist = len*len;
    minDist = _rad1 + _rad2;
    //check if there is a catch
    if(dist<= (minDist * minDist))
    {   return true;    }
    else
    {   return false;   }
}
int gameManager::catchProgress ()
method to check the progress in number of catches made by basket
Definition at line 402 of file gameManager.cpp.
References catchCount.
{
    return catchCount;
}
void gameManager::checkCatch () [private]
method to check if there is a catch by basket calls the collsion detection method to validate a check
Definition at line 354 of file gameManager.cpp.
References basketFallingCharCollision(), catchCount, fallingChars::collectedFlag, basket::drawBasket(), fallingChars::FallingChars_arr, basket::getBasketPos(), basket::getBasketRad(), fallingChars::getFallingCharPos(), fallingChars::getFallingCharType(), fallingChars::getNumberOfFallingChars(), m_Basket, m_cam, m_fallingChars, basket::m_hit, m_transformStack, moveup, randmove, basket::reduceShield(), updateScore(), basket::updateScore(), and updateShield().
{
    float basketRad=m_Basket->getBasketRad();
    float fallingCharRad = 2.0f;
    int fallingCharNum = m_fallingChars->getNumberOfFallingChars();
    for(int i=0;i<fallingCharNum;++i)
    {
        ngl::Vec3 basketPos=m_Basket->getBasketPos();
        ngl::Vec3 * fallingCharPos = m_fallingChars->getFallingCharPos();
        bool charCatch = basketFallingCharCollision(basketPos,
                                                    basketRad,
                                                    fallingCharPos[i],
                                                    fallingCharRad);
        if ((charCatch == true) && (m_fallingChars->collectedFlag[i] == false))
        {
            // increase the catch count
            catchCount++;
            // set the collected flag for the falling character to true,
            // so that it is not available for collection again
            m_fallingChars->collectedFlag[i] = true;
            // get the type of collected falling character
            int ftype = m_fallingChars->getFallingCharType(i);
            m_Basket->updateScore(ftype);
            emit updateScore();
            if (ftype == 3)
            {
                m_Basket->reduceShield();
                emit updateShield();
                m_Basket->m_hit = true;
                m_Basket->drawBasket("Texture",m_transformStack,m_cam);
            }
            m_Basket->m_hit = false;
        }
        if(m_fallingChars->collectedFlag[i] == true)
        {
            float moveside = randmove->randomNumber(2);
            ngl::Vec3 newPos = m_Basket->getBasketPos();
            newPos.m_x -=moveside;
            newPos.m_y +=moveup;
            m_fallingChars->FallingChars_arr[i] = newPos;
        }
    }
}
void gameManager::exit_game () [slot]
slot to exit the game from UI exit button
Definition at line 417 of file gameManager.cpp.
{
    QApplication::exit(EXIT_SUCCESS);
}
void gameManager::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
This virtual function is called once before the first call to paintGL() or resizeGL(), and then once whenever the widget has been assigned a new QGLContext. This function should set up any required OpenGL context rendering flags, defining display lists, etc.
Definition at line 63 of file gameManager.cpp.
References gameEntities::addGameEntity(), catchCount, m_Basket, m_cam, m_fallingChars, m_gameentity, m_gameGround, m_gameWorld, m_hud, m_light, and fallingChars::setFallingCharPos().
{
    // Black Background
    glClearColor(0, 0, 0, 1.0f);
    // enable depth testing for drawing
    glEnable(GL_DEPTH_TEST);
    // we need to initialise the NGL lib, under windows and linux we also need to
    // initialise GLEW, under windows this needs to be done in the app as well
    // as the lib hence the WIN32 define
    ngl::NGLInit *Init = ngl::NGLInit::instance();
    Init->initGlew();
    #ifdef WIN32
        glewInit(); // need a local glew init as well as lib one for windows
    #endif
    // load the shader and set the values
    // grab an instance of shader manager
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    // shader - Phong
    shader->createShaderProgram("Phong");
    // now we are going to create empty shaders for Frag and Vert
    shader->attachShader("PhongVertex",ngl::VERTEX);
    shader->attachShader("PhongFragment",ngl::FRAGMENT);
    // attach the source
    shader->loadShaderSource("PhongVertex","others/Phong.vs");
    shader->loadShaderSource("PhongFragment","others/Phong.fs");
    // compile the shaders
    shader->compileShader("PhongVertex");
    shader->compileShader("PhongFragment");
    // add them to the program
    shader->attachShaderToProgram("Phong","PhongVertex");
    shader->attachShaderToProgram("Phong","PhongFragment");
    // now bind the shader attributes for most NGL primitives we use the following
    // layout attribute 0 is the vertex data (x,y,z)
    shader->bindAttribute("Phong",0,"inVert");
    // attribute 1 is the UV data u,v (if present)
    shader->bindAttribute("Phong",1,"inUV");
    // attribute 2 are the normals x,y,z
    shader->bindAttribute("Phong",2,"inNormal");
    // now we have associated this data we can link the shader
    shader->linkProgramObject("Phong");
    // and make it active ready to load values
    (*shader)["Phong"]->use();
    // texture shader
    ngl::ShaderLib *shader1=ngl::ShaderLib::instance();
    // we are creating a shader called Texture
    shader1->createShaderProgram("Texture");
    // now we are going to create empty shaders for Frag and Vert
    shader1->attachShader("TextureVertex",ngl::VERTEX);
    shader1->attachShader("TextureFragment",ngl::FRAGMENT);
    // attach the source
    shader1->loadShaderSource("TextureVertex","others/TextureVertex.glsl");
    shader1->loadShaderSource("TextureFragment","others/TextureFragment.glsl");
    // compile the shaders
    shader1->compileShader("TextureVertex");
    shader1->compileShader("TextureFragment");
    // add them to the program
    shader1->attachShaderToProgram("Texture","TextureVertex");
    shader1->attachShaderToProgram("Texture","TextureFragment");
    // now we have associated this data we can link the shader
    shader1->linkProgramObject("Texture");
    // (*shader1)["Texture"]->use();
    //CAMERA
    ngl::Vec3 from(0,20,-80);
    ngl::Vec3 to(0,0,0);
    ngl::Vec3 up(0,1,0);
    // load the coordinates to camera
    m_cam= new ngl::Camera(from,to,up,ngl::PERSPECTIVE);
    // set the shape using FOV 45 Aspect Ratio based on Width and Height
    // The final two are near and far clipping planes of 0.5 and 10
    m_cam->setShape(45,(float)720.0/576.0,0.05,350,ngl::PERSPECTIVE);
    shader1->setShaderParam3f("viewerPos",m_cam->getEye().m_x,m_cam->getEye().m_y,m_cam->getEye().m_z);
    //LIGHT -after the camera(to pass the transpose of projection mx to LIGHT, for eye space correction
    ngl::Mat4 iv=m_cam->getViewMatrix();
    iv.transpose();
    m_light = new ngl::Light(ngl::Vec3(50,50,2),ngl::Colour(1,1,1,1),ngl::Colour(1,1,1,1),ngl::DIRECTIONALLIGHT);
    m_light->setAttenuation(1,0,0);
    m_light->setTransform(iv);
    // load these values to the shader as well
    m_light->loadToShader("light");
    //GAME CHARACTERS
    // create the basket with an initial catch count of zero
    catchCount = 0; //no of catches in the basket;
    m_Basket = new basket(ngl::Vec3(0,-30,0),&m_gameentity,m_cam);
    // falling characters
    m_fallingChars = new fallingChars(&m_gameentity,m_cam);
    // set the position o falling characters
    m_fallingChars->setFallingCharPos();
    // game ground
    m_gameGround = new gameGround(&m_gameentity,m_cam);
    // game world/environment
    m_gameWorld = new gameWorld("textures/JungleBackground.png","textures/JungleBackground.png",m_cam);
    //game heads up display text
    m_hud = new ngl::Text(QFont("Arial",30));
    // add GAME ENTITY meshes and textures
    m_gameentity.addGameEntity("basket","models/fruitBasket.obj","textures/wickerBasket.png");
    m_gameentity.addGameEntity("hitbasket","models/gardenBasket.obj","textures/damage.png");
    m_gameentity.addGameEntity("FallingChars_fruit","models/fallingFruit.obj","textures/redfruit.png");
    m_gameentity.addGameEntity("FallingChars_insect","models/insect.obj","textures/greenOrangeInsect.png");
    m_gameentity.addGameEntity("FallingChars_stone","models/stone.obj","textures/rock.png");
    m_gameentity.addGameEntity("GameWorld","models/gameGround.obj","textures/ground.png");
}
void gameManager::loadMatricesToShader (ngl::TransformStack & _tx) [private]
method to load the tx stack (+MVP) to the shader
Parameters:
_tx the transform stack to use for the model part of the matrix
Definition at line 183 of file gameManager.cpp.
References m_cam.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  ngl::Mat4 MVP=m_cam->getVPMatrix() * _tx.getCurrAndGlobal().getMatrix();
  shader->setShaderParamFromMat4("MVP",MVP);
}
void gameManager::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters:
_event the Qt Event structure
Definition at line 428 of file gameManager.cpp.
References clampmouse(), INCREMENT, m_modelPos, m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, m_spinXFace, m_spinYFace, and m_translate.
{
    // note the method buttons() is the button state when event was called
    // this is different from button() which is used to check which button was
    // pressed when the mousePress/Release event is generated
    if(m_rotate && _event->buttons() == Qt::LeftButton)
    {
      int diffx=_event->x()-m_origX;
      int diffy=_event->y()-m_origY;
      //m_spinXFace += (float) 0.5f * diffy;
      m_spinXFace += (float) 0.5f * diffy;
      m_spinYFace += (float) 0.5f * diffx;
      clampmouse (m_spinXFace, 5, 25);
      m_origX = _event->x();
      m_origY = _event->y();
      updateGL();
    }
    // right mouse translate code
    else if(m_translate && _event->buttons() == Qt::RightButton)
    {
      int diffX = (int)(_event->x() - m_origXPos);
      int diffY = (int)(_event->y() - m_origYPos);
      m_origXPos=_event->x();
      m_origYPos=_event->y();
      m_modelPos.m_x += INCREMENT * diffX;
      m_modelPos.m_y -= INCREMENT * diffY;
      updateGL();
    }
}
void gameManager::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 460 of file gameManager.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, and m_translate.
{
    // this method is called when the mouse button is pressed in this case we
    // store the value where the maouse was clicked (x,y) and set the Rotate flag to true
    if(_event->button() == Qt::LeftButton)
    {
      m_origX = _event->x();
      m_origY = _event->y();
      m_rotate =true;
    }
    // right mouse translate mode
    else if(_event->button() == Qt::RightButton)
    {
      m_origXPos = _event->x();
      m_origYPos = _event->y();
      m_translate=true;
    }
}
void gameManager::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 481 of file gameManager.cpp.
References m_rotate, and m_translate.
{
    // this event is called when the mouse button is released
    // we then set Rotate to false
    if (_event->button() == Qt::LeftButton)
    {
        m_rotate=false;
    }
    // right mouse translate mode
    if (_event->button() == Qt::RightButton)
    {
        m_translate=false;
    }
}
void gameManager::moveBasket_gl ()
method to move the basket with every key press updates the basket position with respect to arrow keys in x and z axis calls the move funtion of basket class to update basket position
Definition at line 273 of file gameManager.cpp.
References g_BasketUpdate, m_Basket, m_keysPressed, basket::moveBasket(), and basket::rotateBasket().
{
    // first we reset the movement values
    float xDirection=0.0;
    //float yDirection=0.0;
    float zDirection=0.0;
    float rotation=0.0;
    foreach(Qt::Key key, m_keysPressed)
    {
        switch (key)
        {
            case Qt::Key_Left :  { xDirection =  g_BasketUpdate /*+ m_velo*/; break;}
            case Qt::Key_Right : { xDirection = -g_BasketUpdate /*+ m_velo*/; break;}
            case Qt::Key_Up :    { zDirection =  g_BasketUpdate; break;}
            case Qt::Key_Down :  { zDirection = -g_BasketUpdate; break;}
            case Qt::Key_R :     { rotation=1.0; break;}
            default : break;
        }
    }
    m_Basket->moveBasket(xDirection,zDirection);
    // if the set is non zero size we can update the basket movement
    // then tell openGL to re-draw
    if(m_keysPressed.size() !=0)
    {
        m_Basket->moveBasket(xDirection,zDirection);
        m_Basket->rotateBasket(rotation);
    }
}
void gameManager::moveFallingChars_gl ()
method to call the move method of fallingChars class
Definition at line 303 of file gameManager.cpp.
References m_fallingChars, and fallingChars::move_FallingChars().
{
    m_fallingChars->move_FallingChars();
}
void gameManager::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
This virtual function is called whenever the widget needs to be painted. this is our main drawing routine.
Definition at line 194 of file gameManager.cpp.
References gameWorld::draw(), fallingChars::draw_FallingChars(), basket::drawBasket(), gameGround::drawGameGround(), basket::getBasketShield(), m_Basket, m_cam, m_fallingChars, m_gameGround, m_gameWorld, m_hud, m_modelPos, m_spinXFace, m_spinYFace, m_transformStack, moveBasket_gl(), moveFallingChars_gl(), pauseFLag, and playFlag.
{
  // clear the screen and depth buffer
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  // build our transform stack
  ngl::Transformation trans;
  //trans.setRotation(m_spinX);
  // Rotation based on the mouse position for our global transform
  ngl::Mat4 rotX;
  ngl::Mat4 rotY;
  // create the rotation matrices
  rotX.rotateX(m_spinXFace);
  rotY.rotateY(m_spinYFace);
  // multiply the rotations
  ngl::Mat4 final=rotY*rotX;
  // add the translations
  final.m_m[3][0] = m_modelPos.m_x;
  final.m_m[3][1] = m_modelPos.m_y;
  final.m_m[3][2] = m_modelPos.m_z;
  // set this in the TX stack
  trans.setMatrix(final);
  m_transformStack.setGlobal(trans);
  //draw the game entities
  m_Basket->drawBasket("Texture",m_transformStack,m_cam);
  m_fallingChars->draw_FallingChars("Texture",m_cam);
  m_gameGround->drawGameGround("Texture",m_transformStack,m_cam);
  m_gameWorld->draw("Texture",m_transformStack);
  // check if basket's shield is over. if yes, game over..
  if ((m_Basket->getBasketShield()) <= 0)
  {
       m_hud->setColour(1,1,1);
       m_hud->renderText(20,40,QString("Game Over...!!!"));
       m_hud = new ngl::Text(QFont("Arial",15));
       m_hud->setColour(0.9,0.8,0.7);
       m_hud->renderText(20,100,QString("...u shud have avoided the stones"));
       playFlag = false;
  }
  // continue to move the characters if there is no pause or exit.
  if((playFlag == true) && (pauseFLag == false))
   {
    moveFallingChars_gl();
    moveBasket_gl();
   }
}
int gameManager::playerScore ()
method to return the score
Definition at line 412 of file gameManager.cpp.
References basket::getBasketScore(), and m_Basket.
{
    return(m_Basket->getBasketScore());
}
void gameManager::processKeyDown (QKeyEvent * _event)
processKeyDown passed from the main window class
this method is called from the MainWindow class and passed the key event from that, if we didn't need to process the events in main window we could just overload this as the keyPressEvent and only process here.
Parameters:
*_event a pointer to the QKeyEvent passed from main window class
Definition at line 312 of file gameManager.cpp.
References m_keysPressed.
{
    // add to our keypress set the values of any keys pressed
    m_keysPressed += (Qt::Key)_event->key();
}
void gameManager::processKeyUp (QKeyEvent * _event)
processKeyUp passed from the main window class
in this case this method is called from the MainWindow class and passed the key event from that, if we didn't need to process the events in main window we could just overload this as the keyPressEvent and only process here.
Parameters:
*_event a pointer to the QKeyEvent passed from main window class
Definition at line 322 of file gameManager.cpp.
References m_keysPressed.
{
    // remove from our key set any keys that have been released
    m_keysPressed -= (Qt::Key)_event->key();
}
void gameManager::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
This virtual function is called whenever the widget has been resized. The new size is passed in width and height.
Parameters:
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 175 of file gameManager.cpp.
References m_cam, and m_hud.
{
  glViewport(0,0,_w,_h);
  m_cam->setShape(45,(float)_w/_h,0.5,150,ngl::PERSPECTIVE);
  m_hud->setScreenSize(_w,_h);
}
void gameManager::setPause () [slot]
slot to pause the game from UI pause button
Definition at line 247 of file gameManager.cpp.
References pauseFLag.
{
    pauseFLag = true;
}
void gameManager::setPlay () [slot]
slot to play the game from UI play button
Definition at line 242 of file gameManager.cpp.
References playFlag.
{
    playFlag = true;
}
void gameManager::setResume () [slot]
slot to resume the game from UI resume button
Definition at line 252 of file gameManager.cpp.
References pauseFLag.
{
    pauseFLag = false;
}
int gameManager::shieldLeft ()
method to return the shield value of the basket
Definition at line 407 of file gameManager.cpp.
References basket::getBasketShield(), and m_Basket.
{
    return(m_Basket->getBasketShield());
}
void gameManager::timerEvent (QTimerEvent * _event) [private]
the timer event triggered from the timers
this overloaded method is called every time the timers trigger
Parameters:
_even the event of the timer triggered by Qt
Definition at line 259 of file gameManager.cpp.
References checkCatch(), m_redrawTimer, and m_updateTimer.
{
    // the usual process is to check the event timerID and compare it to
    // any timers we have started with startTimer
    if (_event->timerId() == m_updateTimer)
    {
        checkCatch();
    }
    if (_event->timerId() == m_redrawTimer)
    {
        updateGL();
    }
}
void gameManager::updateScore () [signal]
signal to update the score in UI
void gameManager::updateShield () [signal]
signal to update the shield value in UI
void gameManager::wheelEvent (QWheelEvent * _event) [private]
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 498 of file gameManager.cpp.
References m_modelPos, and ZOOM.
{
    // check the diff of the wheel position (0 means no change)
    if(_event->delta() > 0)
    {
        m_modelPos.m_z+=ZOOM;
    }
    else if(_event->delta() <0 )
    {
        m_modelPos.m_z-=ZOOM;
    }
    updateGL();
}
Member Data Documentation
int gameManager::catchCount [private]
counter to keep track of number of catches
Definition at line 244 of file gameManager.h.
basket* gameManager::m_Basket [private]
the basket class pointer
Definition at line 203 of file gameManager.h.
ngl::Camera* gameManager::m_cam [private]
game Camera
Definition at line 183 of file gameManager.h.
fallingChars* gameManager::m_fallingChars [private]
the fallingChar class pointer
Definition at line 207 of file gameManager.h.
gameEntities gameManager::m_gameentity [private]
the gameEntity class for all game meshes
Definition at line 199 of file gameManager.h.
gameGround* gameManager::m_gameGround [private]
the gameGround class pointer
Definition at line 211 of file gameManager.h.
gameWorld* gameManager::m_gameWorld [private]
the gameWorld class pointer
Definition at line 215 of file gameManager.h.
ngl::Text* gameManager::m_hud [private]
text for game's heads up display
Definition at line 248 of file gameManager.h.
QSet<Qt::Key> gameManager::m_keysPressed [private]
the keys being pressed
Definition at line 191 of file gameManager.h.
ngl::Light* gameManager::m_light [private]
the light
Definition at line 195 of file gameManager.h.
ngl::Vec3 gameManager::m_modelPos [private]
the model position for mouse movement
Definition at line 173 of file gameManager.h.
int gameManager::m_origX [private]
the previous x mouse value
Definition at line 157 of file gameManager.h.
int gameManager::m_origXPos [private]
the previous x mouse value for Position changes
Definition at line 165 of file gameManager.h.
int gameManager::m_origY [private]
the previous y mouse value
Definition at line 161 of file gameManager.h.
int gameManager::m_origYPos [private]
the previous y mouse value for Position changes
Definition at line 169 of file gameManager.h.
int gameManager::m_redrawTimer [private]
Definition at line 179 of file gameManager.h.
bool gameManager::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 149 of file gameManager.h.
int gameManager::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 141 of file gameManager.h.
int gameManager::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 145 of file gameManager.h.
ngl::TransformStack gameManager::m_transformStack [private]
transform stack for drawing
Definition at line 187 of file gameManager.h.
bool gameManager::m_translate [private]
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 153 of file gameManager.h.
int gameManager::m_updateTimer [private]
a timer triggered by the startTimer call in the ctor this is called to update the basket position based on the key presses
Definition at line 178 of file gameManager.h.
bool gameManager::pauseFLag [private]
flag to pause the game
Definition at line 256 of file gameManager.h.
bool gameManager::playFlag [private]
flag to play or stop the game
Definition at line 252 of file gameManager.h.
The documentation for this class was generated from the following files:
gameManager.h
gameManager.cpp