Fruit and Insects: basket Class Reference
basket Class Reference
this class creates the basket which catches the falling characters
#include <basket.h>
Public Member Functions
basket ()
Constructor.
basket (ngl::Vec3 _pos, gameEntities *_m, ngl::Camera *_cam)
Constructor.
~basket ()
basket destructor
void drawBasket (const std::string &_shaderName, ngl::TransformStack &_transformStack, ngl::Camera *_cam)
Draw method for drawing the basket.
void drawBasket (bool _hitval, const std::string &_shaderName, ngl::TransformStack &_transformStack, ngl::Camera *_cam)
void moveBasket (float bx, float bz)
method to move the basket in the game world, in the xz plane
void rotateBasket (float _rot)
method to rotate the basket
void reduceShield ()
Method to reduce the basket shield value.
int getBasketShield ()
Method to get the basket shield value.
void updateScore (int &_type)
Method to update the score of the player according to number of catches and type of falling characters.
int getBasketScore ()
Method to get the score.
bool isHit () const
Method to check the flag status of basket if it is hit by stone.
void setHit ()
Method to set the flag status of basket when hit by stone.
void setnotHit ()
Method to reset the flag status of basket to not-hit.
ngl::Vec3 getBasketPos ()
Method to get basket's position.
float getBasketRad ()
Method to get basket's radius.
Public Attributes
bool m_hit
boolean to determine the basket status if it is hit by stone or not
Private Member Functions
void loadMatricesToShader (ngl::TransformStack &_tx, ngl::Camera *_cam) const
load all the transform values to the shader
Private Attributes
ngl::Vec3 m_basketPos
the position of the basket
float m_basketRot
basket rotation
const gameEntities * m_GameEntity
game entity's pointer to draw the basket
const ngl::Camera * m_camera
the camera
int m_basketShield
shield strength of the basket, with a default value of 10
int m_basketScore
basket/player's score
float m_basketRad
basket radius
Detailed Description
this class creates the basket which catches the falling characters
Definition at line 35 of file basket.h.
Constructor & Destructor Documentation
basket::basket ()
Constructor.
Definition at line 36 of file basket.cpp.
References m_basketPos, m_basketRad, m_basketScore, and m_basketShield.
{
    //basket radius
    m_basketRad = 5;
    //basket position
    m_basketPos.set(0,-25,0);
    //set the basket/player's initial score to null
    m_basketScore = 0;
    //the initial shield for the player/basket
    m_basketShield = 10;
}
basket::basket (ngl::Vec3 _pos, gameEntities * _m, ngl::Camera * _cam)
Constructor.
Parameters:
[in] _pos basket position
[in] _m game entity mesh
[in] _cam camera
Definition at line 11 of file basket.cpp.
References m_basketPos, m_basketRad, m_basketRot, m_basketScore, m_basketShield, m_camera, m_GameEntity, and m_hit.
{
//initialze the basket
    //basket radius
    m_basketRad = 5;
    //basket position
    m_basketPos  = _pos;
    // the game entity mesh
    m_GameEntity = _m;
    //the camera
    m_camera = _cam;
    //basket's rotation
    m_basketRot  = 0;
    //set the basket/player's initial score to null
    m_basketScore = 0;
    //the initial shield for the player/basket
    m_basketShield = 10;
    //basket's flag to check if hit by stone, set to 'false' initially
    m_hit=false;
}
basket::~basket ()
basket destructor
Definition at line 48 of file basket.cpp.
References m_GameEntity.
{
    delete m_GameEntity;
}
Member Function Documentation
void basket::drawBasket (bool _hitval, const std::string & _shaderName, ngl::TransformStack & _transformStack, ngl::Camera * _cam)
void basket::drawBasket (const std::string & _shaderName, ngl::TransformStack & _transformStack, ngl::Camera * _cam)
Draw method for drawing the basket.
Parameters:
[in] _shaderName the shader
[in] _transformStack the transformation stack
[in] _cam the camera
Definition at line 54 of file basket.cpp.
References gameEntities::draw(), loadMatricesToShader(), m_basketPos, m_basketRot, m_GameEntity, and m_hit.
{
    //create an instance of the shader
    ngl::ShaderLib *shader = ngl::ShaderLib::instance();
    shader->use(_shaderName);
    //the camera eye is set to basket's position
    ngl::Vec4 _pos;
    _pos.set(m_basketPos);
    _pos.set(m_basketPos.m_x,m_basketPos.m_y+30,m_basketPos.m_z-60);
    _cam->setEye(_pos);
    //transformations
    _transformStack.pushTransform();
    {
        _transformStack.setPosition(m_basketPos);
        _transformStack.setRotation(0,m_basketRot,0);
        loadMatricesToShader(_transformStack,_cam);
        //check if the basket is hit by stone
        if (m_hit)
        {
            // if yes, draw the mesh for hit basket
            m_GameEntity->draw("hitbasket");
        }
        else
        {
            m_GameEntity->draw("basket");
        }
        //draw the normal basket mesh
        m_GameEntity->draw("basket");
    }
     _transformStack.popTransform();
    glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
}
ngl::Vec3 basket::getBasketPos ()
Method to get basket's position.
Definition at line 157 of file basket.cpp.
References m_basketPos.
{
    return m_basketPos;
}
float basket::getBasketRad ()
Method to get basket's radius.
Definition at line 162 of file basket.cpp.
References m_basketRad.
{
    return m_basketRad;
}
int basket::getBasketScore ()
Method to get the score.
Definition at line 152 of file basket.cpp.
References m_basketScore.
{
    return m_basketScore;
}
int basket::getBasketShield ()
Method to get the basket shield value.
Definition at line 131 of file basket.cpp.
References m_basketShield.
{
    return m_basketShield;
}
bool basket::isHit () const [inline]
Method to check the flag status of basket if it is hit by stone.
Definition at line 115 of file basket.h.
References m_hit.
{return m_hit;}
void basket::loadMatricesToShader (ngl::TransformStack & _tx, ngl::Camera * _cam) const [private]
load all the transform values to the shader
Parameters:
[in] _tx the current transform to load
[in] _cam the camera
Definition at line 167 of file basket.cpp.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    ngl::Mat4 MV;
    ngl::Mat4 MVP;
    MV=_tx.getCurrAndGlobal().getMatrix()*_cam->getViewMatrix() ;
    MVP=MV*_cam->getProjectionMatrix();
    shader->setShaderParamFromMat4("MVP",MVP);
}
void basket::moveBasket (float bx, float bz)
method to move the basket in the game world, in the xz plane
Parameters:
[in] _bx - the x coordinate of the basket position
[in] _bz - the z coordinate of the basket position
Definition at line 103 of file basket.cpp.
References clamp(), m_basketPos, s_xExtents, and s_zExtents.
{
    //updating the basket position in x and z axis
    m_basketPos.m_x += bx;
    m_basketPos.m_z += bz;
    // making sure that the basket stays in the permissible area
    clamp(m_basketPos.m_x,-s_xExtents,+s_xExtents);
    clamp(m_basketPos.m_z,-s_zExtents,+s_zExtents);
}
void basket::reduceShield ()
Method to reduce the basket shield value.
Definition at line 125 of file basket.cpp.
References m_basketShield.
{
    //reducing the shield value by 1 if hit by a stone
    m_basketShield = m_basketShield - 1;
}
void basket::rotateBasket (float _rot)
method to rotate the basket
Parameters:
[in] _rot - the rotation value for the basket
Definition at line 117 of file basket.cpp.
References m_basketRot.
{
    //basket's rotation
    m_basketRot += _rot;
}
void basket::setHit () [inline]
Method to set the flag status of basket when hit by stone.
Definition at line 119 of file basket.h.
References m_hit.
{m_hit=true;}
void basket::setnotHit () [inline]
Method to reset the flag status of basket to not-hit.
Definition at line 123 of file basket.h.
References m_hit.
{m_hit=false;}
void basket::updateScore (int & _type)
Method to update the score of the player according to number of catches and type of falling characters.
Parameters:
[in] _type the type of falling character caught
Definition at line 136 of file basket.cpp.
References m_basketScore.
{
    //for falling chartype - fruit
    if(_type == 1)
    {
        //increase score
        m_basketScore+=100;
    }
    //for falling chartype - insect
    if(_type == 2)
    {
        //decrease score
        m_basketScore-=50;
    }
}
Member Data Documentation
ngl::Vec3 basket::m_basketPos [private]
the position of the basket
Definition at line 138 of file basket.h.
float basket::m_basketRad [private]
basket radius
Definition at line 162 of file basket.h.
float basket::m_basketRot [private]
basket rotation
Definition at line 142 of file basket.h.
int basket::m_basketScore [private]
basket/player's score
Definition at line 158 of file basket.h.
int basket::m_basketShield [private]
shield strength of the basket, with a default value of 10
Definition at line 154 of file basket.h.
const ngl::Camera* basket::m_camera [private]
the camera
Definition at line 150 of file basket.h.
const gameEntities* basket::m_GameEntity [private]
game entity's pointer to draw the basket
Definition at line 146 of file basket.h.
bool basket::m_hit
boolean to determine the basket status if it is hit by stone or not
Definition at line 59 of file basket.h.
The documentation for this class was generated from the following files:
basket.h
basket.cpp