Fruit and Insects: fallingChars Class Reference
fallingChars Class Reference
this class creates the falling characters of type - fruit, insects, and stones the class associates the id, points, type with each object
#include <fallingChars.h>
Public Types
enum fallingCharsType { fruit = 1, insect = 2, stone = 3 }
falling character types
Public Member Functions
fallingChars ()
Constructor.
fallingChars (gameEntities *_m, ngl::Camera *_cam)
Constructor.
~fallingChars ()
deonstructor
void draw_FallingChars (const std::string &_shader, ngl::Camera *_cam)
Draw method for drawing the falling characters.
void move_FallingChars ()
method to move the falling characters in y direction only
int getFallingCharType (int &i)
method to get falling character type
int getFallingCharID (int &current)
method to get falling character ID
ngl::Vec3 * getFallingCharPos ()
method to get falling haracter position
int getFallingCharRad ()
method to get falling character radius
int getFallingCharPoints (int &i)
method to get falling character points for each type
void setFallingCharTypePoints (int &i)
method to set falling character type and points
void setFallingCharPos ()
method to set falling character position
int getNumberOfFallingChars ()
method to get the number of falling characters
Public Attributes
float m_fradius
falling character radius
ngl::Vec3 currentFallingCharPos
current falling character position
int currentFallingChar
current falling character
bool * collectedFlag
status for each falling character if it is collected or not
ngl::Vec3 * FallingChars_arr
falling character positions
Private Attributes
const gameEntities * m_gameentity
game entity
const ngl::Camera * f_camera
camera
ngl::TransformStack f_transform
transformation stack
GLfloat * m_colours
float colour values
int FallingChars_points
points for falling characters
ngl::TransformStack FallingChars_transform
transformation stack
fallingCharsType chartype
charater type
int * m_id
id for each falling character
Detailed Description
this class creates the falling characters of type - fruit, insects, and stones the class associates the id, points, type with each object
Definition at line 39 of file fallingChars.h.
Member Enumeration Documentation
enum fallingChars::fallingCharsType
falling character types
Enumerator:
fruit
insect
stone
Definition at line 73 of file fallingChars.h.
{fruit = 1, insect = 2, stone = 3};
Constructor & Destructor Documentation
fallingChars::fallingChars ()
Constructor.
Definition at line 12 of file fallingChars.cpp.
References chartype, FallingChars_arr, fruit, m_fradius, and m_id.
{
     m_fradius = 2;
     m_id = NULL;
     FallingChars_arr->set(0.0f,30.0f,0.0f);
     chartype = fruit;
}
fallingChars::fallingChars (gameEntities * _m, ngl::Camera * _cam)
Constructor.
Parameters:
[in] _m game entity mesh
[in] _cam camera
Definition at line 20 of file fallingChars.cpp.
References chartype, f_camera, fruit, m_fradius, m_gameentity, and m_id.
{
    m_gameentity= _m;
    f_camera = _cam;
    m_fradius = 2;
    m_id = NULL;
    chartype = fruit;
}
fallingChars::~fallingChars ()
deonstructor
deconstructor
Definition at line 34 of file fallingChars.cpp.
References collectedFlag, FallingChars_arr, m_gameentity, and m_id.
{
    delete m_gameentity;
    delete m_id;
    delete FallingChars_arr;
    delete collectedFlag;
}
Member Function Documentation
void fallingChars::draw_FallingChars (const std::string & _shader, ngl::Camera * _cam)
Draw method for drawing the falling characters.
Parameters:
[in] _shader the shader
[in] _cam the camera
Definition at line 89 of file fallingChars.cpp.
References gameEntities::draw(), FallingChars_arr, FallingChars_num, FallingChars_transform, getFallingCharType(), and m_gameentity.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)[_shader]->use();
    for( int i=0; i<FallingChars_num; ++i)
    {
        FallingChars_transform.getCurrentTransform().setPosition(FallingChars_arr[i]);
        ngl::Mat4 MVP = FallingChars_transform.getCurrentTransform().getMatrix() * _cam->getVPMatrix();
        shader->setShaderParamFromMat4("MVP",MVP);
        int ctype = getFallingCharType(i);
        if (ctype == 1)
            {
                m_gameentity->draw("FallingChars_fruit");
            }
            else {
                if (ctype == 2)
                    {
                    m_gameentity->draw("FallingChars_insect");
                    }
                else {if (ctype == 3)
{
                            m_gameentity->draw("FallingChars_stone");
                        }
                      }
                    }
    }
 }
int fallingChars::getFallingCharID (int & current)
method to get falling character ID
Definition at line 167 of file fallingChars.cpp.
References m_id.
{
    return m_id[current];
}
int fallingChars::getFallingCharPoints (int & i)
method to get falling character points for each type
Definition at line 139 of file fallingChars.cpp.
References m_id.
{
    if (m_id[i]<60)
    {
        return 100;
    }
    else{
        if (m_id[i]>80)
        {
            return 0;
        }
        else
        {
            return -50;
        }
    }
}
ngl::Vec3 * fallingChars::getFallingCharPos ()
method to get falling haracter position
Definition at line 157 of file fallingChars.cpp.
References FallingChars_arr.
{
    return FallingChars_arr;
}
int fallingChars::getFallingCharRad ()
method to get falling character radius
Definition at line 162 of file fallingChars.cpp.
References m_fradius.
{
    return m_fradius;
}
int fallingChars::getFallingCharType (int & i)
method to get falling character type
Definition at line 121 of file fallingChars.cpp.
References fruit, insect, m_id, and stone.
{
    if (m_id[i]<60)
    {
        return fruit;
    }
    else{
        if (m_id[i]>80)
        {
            return stone;
        }
        else
        {
            return insect;
        }
    }
}
int fallingChars::getNumberOfFallingChars ()
method to get the number of falling characters
Definition at line 43 of file fallingChars.cpp.
References FallingChars_num.
{
    return FallingChars_num;
}
void fallingChars::move_FallingChars ()
method to move the falling characters in y direction only
Definition at line 172 of file fallingChars.cpp.
References collectedFlag, FallingChars_arr, and FallingChars_num.
{
    for(int i=0;i<FallingChars_num;++i)
    {
        if((FallingChars_arr[i].m_y <= -26.0) && (collectedFlag[i] == false))
        {
            FallingChars_arr[i].m_y = 30.0;
        }
        ngl::Random *rand=ngl::Random::instance();
        float randfall=10*(rand->randomPositiveNumber());
        FallingChars_arr[i].m_y-=1/randfall;  //reduce y to make them fall
    }
}
void fallingChars::setFallingCharPos ()
method to set falling character position
Definition at line 48 of file fallingChars.cpp.
References collectedFlag, FallingChars_arr, FallingChars_num, m_id, and setFallingCharTypePoints().
{
    FallingChars_arr = new ngl::Vec3[FallingChars_num];
    m_id = new int[FallingChars_num];
    ngl::Random *rand=ngl::Random::instance();
    for(int f =0; f<FallingChars_num; ++f)
    {
        //generating random position for the characters
        FallingChars_arr[f]=rand->getRandomVec3();
        FallingChars_arr[f].m_x=FallingChars_arr[f].m_x*10.0f*3.0f;
        FallingChars_arr[f].m_y = 30.0f;
        FallingChars_arr[f].m_z=FallingChars_arr[f].m_z*23.0f;
        m_id[f]=f;
        collectedFlag[f] = false;
        setFallingCharTypePoints(f);
    }
}
void fallingChars::setFallingCharTypePoints (int & i)
method to set falling character type and points
Definition at line 67 of file fallingChars.cpp.
References chartype, FallingChars_points, fruit, insect, m_id, and stone.
{
    if (m_id[i]<60)
    {
        chartype = fruit;
        FallingChars_points = 100;
    }
    else{
        if (m_id[i]>80)
        {
            chartype = stone;
            FallingChars_points = 0;
        }
        else
        {
            chartype = insect;
            FallingChars_points = -50;
        }
    }
}
Member Data Documentation
fallingCharsType fallingChars::chartype [private]
charater type
Definition at line 155 of file fallingChars.h.
bool* fallingChars::collectedFlag
status for each falling character if it is collected or not
Definition at line 121 of file fallingChars.h.
int fallingChars::currentFallingChar
current falling character
Definition at line 113 of file fallingChars.h.
ngl::Vec3 fallingChars::currentFallingCharPos
current falling character position
Definition at line 109 of file fallingChars.h.
const ngl::Camera* fallingChars::f_camera [private]
camera
Definition at line 135 of file fallingChars.h.
ngl::TransformStack fallingChars::f_transform [private]
transformation stack
Definition at line 139 of file fallingChars.h.
ngl::Vec3* fallingChars::FallingChars_arr
falling character positions
Definition at line 125 of file fallingChars.h.
int fallingChars::FallingChars_points [private]
points for falling characters
Definition at line 147 of file fallingChars.h.
ngl::TransformStack fallingChars::FallingChars_transform [private]
transformation stack
Definition at line 151 of file fallingChars.h.
GLfloat* fallingChars::m_colours [private]
float colour values
Definition at line 143 of file fallingChars.h.
float fallingChars::m_fradius
falling character radius
Definition at line 101 of file fallingChars.h.
const gameEntities* fallingChars::m_gameentity [private]
game entity
Definition at line 131 of file fallingChars.h.
int* fallingChars::m_id [private]
id for each falling character
Definition at line 159 of file fallingChars.h.
The documentation for this class was generated from the following files:
fallingChars.h
fallingChars.cpp