Fruit and Insects: MainWindow Class Reference
MainWindow Class Reference
the main re-sizable window which contains a GLWindow widget used to hold our basic gl applications
#include <MainWindow.h>
Signals
void updateBar ()
signal to update the progress bar in the user interface
Public Member Functions
MainWindow (QWidget *parent=0)
ctor basically we create a GLWindow and parent it to this window so our GLWindow is the main canvas
~MainWindow ()
dtor
bool catchprog ()
method to check the progress of basket catches with every key press
Public Attributes
int prevCatchCount = 0
initialize the catch count to zero to for previous catch
int currCatchCount = 0
initialize the catch count to zero to for current catch
Protected Member Functions
void keyPressEvent (QKeyEvent *_event)
override the keyPressEvent inherited from QObject so we can handle key presses.
void keyReleaseEvent (QKeyEvent *_event)
override the keyPressEvent inherited from QObject so we can handle key presses.
Private Slots
void updateProgBar ()
slot to update the progress bar in the user interface
void updateShieldLabel ()
slot to update the label for player's shield
void updateScoreLabel ()
slot to update the label for player's score
Private Attributes
gameManager * m_gl
our gl window created in gameManager
Ui::MainWindow * m_ui
main window user interface
Detailed Description
the main re-sizable window which contains a GLWindow widget used to hold our basic gl applications
Definition at line 32 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) [explicit]
ctor basically we create a GLWindow and parent it to this window so our GLWindow is the main canvas
the main re-sizable window which contains a GLWindow widget used to hold our basic gl applications
Definition at line 9 of file MainWindow.cpp.
References m_gl, m_ui, updateBar(), updateProgBar(), updateScoreLabel(), and updateShieldLabel().
                                      :
    QMainWindow(parent),
    m_ui(new Ui::MainWindow)
{
    m_ui->setupUi(this);
    //create GL window and parent it to this
    m_gl = new gameManager(this);
    //set main grid layout for the main window
    m_ui->s_mainWindowGridLayout->addWidget(m_gl,0,0,2,1);
    // grab keyboard input from the central widget
    // that houses the main gameplay
    m_ui->centralwidget->grabKeyboard();
    // the play button
    connect(m_ui->m_play,SIGNAL(clicked()),m_gl,SLOT(setPlay()));
    // the pause button
    connect(m_ui->m_pause,SIGNAL(clicked()),m_gl,SLOT(setPause()));
    // the game resume button
    connect(m_ui->m_resume,SIGNAL(clicked()),m_gl,SLOT(setResume()));
    // the game exit button
    connect(m_ui->m_exit,SIGNAL(clicked()),m_gl,SLOT(exit_game()));
    //progress bar
    connect(this,SIGNAL(updateBar()),this,SLOT(updateProgBar()));
    // label to update the basket's shield value
    connect(m_gl,SIGNAL(updateShield()),this,SLOT(updateShieldLabel()));
    // label to update player's score value
    connect(m_gl,SIGNAL(updateScore()),this,SLOT(updateScoreLabel()));
}
//----------------------------------------------------------------------------------------------------------------------
MainWindow::~MainWindow ()
dtor
Definition at line 37 of file MainWindow.cpp.
References m_gl, and m_ui.
{
    delete m_ui;
    delete m_gl;
}
Member Function Documentation
bool MainWindow::catchprog ()
method to check the progress of basket catches with every key press
Definition at line 71 of file MainWindow.cpp.
References gameManager::catchProgress(), currCatchCount, m_gl, prevCatchCount, and updateBar().
{
    //if there is an increase in catch count, then return true
    currCatchCount = m_gl->catchProgress();
    if (prevCatchCount < currCatchCount)
    {
        // emit the signal to update bar
        emit updateBar();
        prevCatchCount = currCatchCount;
        return true;
    }
    else
    {
        prevCatchCount = currCatchCount;
        return false;
    }
}
void MainWindow::keyPressEvent (QKeyEvent * _event) [protected]
override the keyPressEvent inherited from QObject so we can handle key presses.
Parameters:
[in] _event the event to process
Definition at line 50 of file MainWindow.cpp.
References catchprog(), m_gl, gameManager::moveBasket_gl(), and gameManager::processKeyDown().
{
    // check if there is any update in number of catches
    catchprog();
    // this method is called every time the main window recives a key event.
    // we then switch on the key value and set the camera in the GLWindow
    switch (_event->key())
    {
      case Qt::Key_Escape : QApplication::exit(EXIT_SUCCESS); break;
      case Qt::Key_F : showFullScreen(); break;
      case Qt::Key_N : showNormal(); break;
      case Qt::Key_Up: m_gl->moveBasket_gl();
      default : break;
    }
    // once we have processed any key here pass the event
    // onto the GLWindow class to do more processing
    m_gl->processKeyDown(_event);
}
void MainWindow::keyReleaseEvent (QKeyEvent * _event) [protected]
override the keyPressEvent inherited from QObject so we can handle key presses.
Parameters:
[in] _event the event to process
Definition at line 43 of file MainWindow.cpp.
References m_gl, and gameManager::processKeyUp().
{
    // once we have processed any key here pass the event
    // onto the GLWindow class to do more processing
    m_gl->processKeyUp(_event);
}
void MainWindow::updateBar () [signal]
signal to update the progress bar in the user interface
void MainWindow::updateProgBar () [private, slot]
slot to update the progress bar in the user interface
Definition at line 89 of file MainWindow.cpp.
References gameManager::catchProgress(), m_gl, and m_ui.
{
    int progvalue = m_gl->catchProgress();
    //progress = value
    //std::cout<<"\n on_m_progress_valueChanged: value = "<<value;
    m_ui->m_progress->setValue(progvalue);
}
void MainWindow::updateScoreLabel () [private, slot]
slot to update the label for player's score
Definition at line 111 of file MainWindow.cpp.
References m_gl, m_ui, gameManager::playerScore(), and value_to_string().
{
    int scoreVal = m_gl->playerScore();
    std::string score = value_to_string(scoreVal);
    m_ui->m_score->setText(score.c_str());
}
void MainWindow::updateShieldLabel () [private, slot]
slot to update the label for player's shield
Definition at line 104 of file MainWindow.cpp.
References m_gl, m_ui, gameManager::shieldLeft(), and value_to_string().
{
    int shieldVal = m_gl->shieldLeft();
    std::string shield =  value_to_string(shieldVal);
    m_ui->m_shield->setText(shield.c_str());
}
Member Data Documentation
int MainWindow::currCatchCount = 0
initialize the catch count to zero to for current catch
Definition at line 68 of file MainWindow.h.
gameManager* MainWindow::m_gl [private]
our gl window created in gameManager
Definition at line 95 of file MainWindow.h.
Ui::MainWindow* MainWindow::m_ui [private]
main window user interface
Definition at line 99 of file MainWindow.h.
int MainWindow::prevCatchCount = 0
initialize the catch count to zero to for previous catch
Definition at line 64 of file MainWindow.h.
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp